version: '3.9'

services:
  # MongoDB service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes: 
      - mongo_db:/data/db

  # MongoDB data
  mongo-seed:
    build: ./Database
    depends_on:
      - mongo_db

  # Node API service
  api:
    build: .
    ports:
     - 3000:3000
    environment:
      DATABASE_URL: mongodb://mongo_db/CanvasBuilderDB
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}