GET http://localhost:3000/canvases

###

GET http://localhost:3000/CanvasBuilderDB/627ce2d136ebbe6d603cb55b

###

POST http://localhost:3000/canvases
Content-Type: application/json

{
    "name": "Software Testing Canvas",
    "tiles": 10,
    "type": "Canvas",
    "imagename": "content_strategy_canvas.PNG",
    "Tile": [
        { "text": "Components", "cols": 20, "rows": 20, "color": "white" },
        { "text": "Checking", "cols": 20, "rows": 25, "color": "white" },
        { "text": "Basis", "cols": 20, "rows": 30, "color": "white" },
        { "text": "Manual", "cols": 20, "rows": 20, "color": "white" },
        { "text": "Connection", "cols": 20, "rows": 25, "color": "white" },
        { "text": "Features", "cols": 20, "rows": 30, "color": "white" },
        { "text": "Automated", "cols": 20, "rows": 30, "color": "white" },
        { "text": "Exploring", "cols": 20, "rows": 25, "color": "white" },
        { "text": "Configuration", "cols": 20, "rows": 25, "color": "white" },
        { "text": "Oracle", "cols": 20, "rows": 20, "color": "white" }
    ]
}

###
DELETE http://localhost:3000/CanvasBuilderDB/627e497ac69ad78c84c719e2

###

PATCH http://localhost:3000/CanvasBuilderDB/627e34472ac1e1fef0e8fcbd
Content-Type: application/json

{
    "name": "Buisness Model Canvas"
}