GET http://localhost:3000/canvases

###

GET http://localhost:3000/templates

###

GET http://localhost:3000/canvases/62875f35e052e17be61fb16e

###

GET http://localhost:3000/templates/62a2181947c89b46ee7104ca

###

POST http://localhost:3000/canvases
Content-Type: application/json

{
    "name": "Software Testing Canvas",
    "tiles": 10,
    "type": "Canvas",
    "imagename": "content_strategy_canvas.PNG",
    "Tile": [
        { "text": "Components", "cols": 20, "rows": 20, "color": "white" },
        { "text": "Checking", "cols": 20, "rows": 25, "color": "white" },
        { "text": "Basis", "cols": 20, "rows": 30, "color": "white" },
        { "text": "Manual", "cols": 20, "rows": 20, "color": "white" },
        { "text": "Connection", "cols": 20, "rows": 25, "color": "white" },
        { "text": "Features", "cols": 20, "rows": 30, "color": "white" },
        { "text": "Automated", "cols": 20, "rows": 30, "color": "white" },
        { "text": "Exploring", "cols": 20, "rows": 25, "color": "white" },
        { "text": "Configuration", "cols": 20, "rows": 25, "color": "white" },
        { "text": "Oracle", "cols": 20, "rows": 20, "color": "white" }
    ]
}

###

POST http://localhost:3000/templates
Content-Type: application/json

{
    "name": "3x3 Template",
    "tiles": 4,
    "type": "Template",
    "imagename": "4x4_template.PNG",
    "Tile": [
        {"cols": 50, "rows": 25, "color": "white"},
        {"cols": 50, "rows": 25, "color": "white"},
        {"cols": 50, "rows": 25, "color": "white"},
        {"cols": 50, "rows": 25, "color": "white"}
    ]
}

###
DELETE http://localhost:3000/canvases/627e497ac69ad78c84c719e2

###

DELETE http://localhost:3000/templates/62a2135b8f9776269921cf14

###

PATCH http://localhost:3000/templates/62a2181947c89b46ee7104ca
Content-Type: application/json

{
    "name": "2x2 Template"
}